// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChqO1na6pYfeAAJ9knELDp6i2GYQiQmos',
    appId: '1:176366182055:web:1fed5a242e06e628fa4582',
    messagingSenderId: '176366182055',
    projectId: 'socialmediaapp-c2f79',
    authDomain: 'socialmediaapp-c2f79.firebaseapp.com',
    storageBucket: 'socialmediaapp-c2f79.appspot.com',
    measurementId: 'G-F6YWEMVMFC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgY6WAhlcKO4z9lKh1aK5GDDlFE8Hhejc',
    appId: '1:176366182055:android:c9557164f5a354e8fa4582',
    messagingSenderId: '176366182055',
    projectId: 'socialmediaapp-c2f79',
    storageBucket: 'socialmediaapp-c2f79.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD87TTXGHMQYf2GqQSoGWxc2gVY4GaBZCw',
    appId: '1:176366182055:ios:c0ce39429601a234fa4582',
    messagingSenderId: '176366182055',
    projectId: 'socialmediaapp-c2f79',
    storageBucket: 'socialmediaapp-c2f79.appspot.com',
    androidClientId: '176366182055-ajl38atebqtrn4m1erd21buu7nhaaggi.apps.googleusercontent.com',
    iosClientId: '176366182055-8snlpkrupc4gdlnpb1ak7onnml74ekse.apps.googleusercontent.com',
    iosBundleId: 'com.mikkyboy.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD87TTXGHMQYf2GqQSoGWxc2gVY4GaBZCw',
    appId: '1:176366182055:ios:0b48636793320f17fa4582',
    messagingSenderId: '176366182055',
    projectId: 'socialmediaapp-c2f79',
    storageBucket: 'socialmediaapp-c2f79.appspot.com',
    androidClientId: '176366182055-ajl38atebqtrn4m1erd21buu7nhaaggi.apps.googleusercontent.com',
    iosClientId: '176366182055-1vlprlidot3376ltb14b44bej988ic3e.apps.googleusercontent.com',
    iosBundleId: 'socialmediaapp.com',
  );
}
